kind: PersistentVolume
apiVersion: v1
metadata:
  name: operation-service-mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/nathan/Projects/skaioskit/server/operation-service/working/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: operation-service-mysql-pv-claim
  labels:
    app: operation-service
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta2 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: operation-service-mysql
  labels:
    app: operation-service-mysql
spec:
  selector:
    matchLabels:
      app: operation-service-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: operation-service-mysql
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7.22
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_USER
          value: skaioskit
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: operation
          # TODO: use secrets
          #  valueFrom:
          #    secretKeyRef:
          #      name: mysql-pass
          #      key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: operation-service-mysql-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: operation-service-mysql
spec:
  selector:
    app: operation-service-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: operation-service
  labels:
    app: operation-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: operation-service
    spec:
      containers:
      - name: operation-service
        image: localhost:5000/skaioskit/operation-service:latest
        imagePullPolicy: Always
        command: 
        - /operation
        - serve
        ports:
        - containerPort: 80
        env:
        - name: BUILD_DATETIME
          value: "{{BUILD_TIME}}"
---
kind: Service
apiVersion: v1
metadata:
  name: operation-service
spec:
  selector:
    app: operation-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: operation-service-lb
spec:
  type: NodePort
  selector:
    app: operation-service
  ports:
  - port: 80
    nodePort: 30080
---
